version: '3.8'

services:
  ia-turbo:
    container_name: ia-turbo-fullstack
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "3001:3001"
    env_file:
      - .env
    working_dir: /app/backend
    command: sh -c "cd /app/backend && npm install && node server.js & cd /app/frontend && npm install && npm run build && npx serve -s dist -l 80"
    restart: always