version: '3.8'

services:
<<<<<<< HEAD
  ia-turbo:
=======
  ia-backend:
>>>>>>> origin/main
    container_name: ia-turbo-backend
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: always
